# NumPy Arrays
## Overview
- main object: homogeneous multidimensional array
- table of elements (usually numbers)
- all of the same type
- indexed by a tuple of positive integers
- axes: dimensions
- class of NumPy's array is: ndarray
    - different from standard python class array.array
        - only handles 1-dimensional arrays
        - less functionality

### Example:
- a point in [1,2,1] has one axis
- the axis has 3 elements in it => length of the axis is 3

In [ ]:
# how many axes in the example below?
# what's the length of each axis?
[[1, 2, 3,],
 [0, 2, 4]]

### Important attributes of an ndarray object:

- **ndarray.ndim**: 
    - number of dimensions (axes) of an array
- **ndarray.shape**: 
    - the dimensions of the array
    - returns a tuple of integers describing size of array in each dimension
    - e.g. for a matrix w/ n rows & m columns => shape will be (n,m)
    - length of the shape tuple (n,m) is thus, the # of axes, ndim
- **ndarray.size**:
    - total # of elements of the array
    - equals the product of elements of shape


In [3]:
# Example:
# create an ndarray with 3 rows, 5 columns, and 
# fill with number incrementing by 1 from 0 to 14

import numpy as np
m = np.arange(15).reshape(3,5)
print('shape:', m.shape)
print('ndim:', m.ndim)
print('size:', m.size)


shape: (3, 5)
ndim: 2
size: 15


## Create Arrays

### From a python list or tuple, using array function:

In [6]:
nums = [2,3,4]
a = np.array(nums)
a

array([2, 3, 4])

In [7]:
# or:
a = np.array([2,3,4])
a

array([2, 3, 4])

#### be careful, need to pass a list inside the round brackets

In [9]:
# wrong way:
a = np.array(1,2,3,4)
# fix: a = np.array([1,2,3,4])

ValueError: only 2 non-keyword arguments accepted

In [27]:
b = np.array([(1.5,2,3), (4,5,6)]) 
print(b) #notice the dimensions of b 
print(b.dtype) #notice the dtype of b

[[1.5 2.  3. ]
 [4.  5.  6. ]]
float64


## Create Arrays

### using np.zeros, np.ones, np.empty

In [17]:
np.zeros((3,4)) # all zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4)) # all ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((2,3)) #initial content is random

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [84]:
#Create an array with random values:
np.random.randn(3,4)

array([[-0.61835717,  1.76987793, -1.45545215, -0.36255746],
       [-2.50314102, -1.5341043 , -1.00731344, -0.32693971],
       [ 0.76593285,  1.11872014,  0.85114414, -0.12450567]])

## Create Arrays that are sequences of numbers
### using np.arange

In [24]:
np.arange(10,100,5) #1d array
#sequence of numbers from 10 
#up to (not including) 100, incrementing each by 5

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [22]:
np.arange(0, 10, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [25]:
np.arange(10,100,5).reshape(3,6) #2d array, 3 rows, 6 cols

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [26]:
np.arange(10,100,5).reshape(6,3)

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80],
       [85, 90, 95]])

### Specifying type for arrays:

`array2d_float = np.array(list2, dtype = 'float')`

(or 'str', 'object', 'bool')

- Convert type

`array2d.astype('int')`

- Convert back to list:

`array2d.tolist()`


### Printing arrays
``np.set_printoptions(threshold=np.nan)`` 

=> for large arrays: print the entire array without skipping the central part

### Basic Operations
- element wise

In [73]:
a = np.arange(20,60, 10)
b = np.arange(4)
print(a)
print(b)
print('elem-wise product of a and b:', a*b)
print('sum of a and b:', a+b) # or use np.add(a,b)
print(b**2)
print(a*2)
print(b/a)
print(a<50)

[20 30 40 50]
[0 1 2 3]
elem-wise product of a and b: [  0  30  80 150]
sum of a and b: [20 31 42 53]
[0 1 4 9]
[ 40  60  80 100]
[0.         0.03333333 0.05       0.06      ]
[ True  True  True False]


In [82]:
# matrix product
a1 = np.array([[1,1], [1,2]])
a2 = np.array([[2,0], [3,5]])
print(a1)
print(a2)
print(a1.dot(a2))
print(a1@a2) #same as previous line

[[1 1]
 [1 2]]
[[2 0]
 [3 5]]
[[ 5  5]
 [ 8 10]]
[[ 5  5]
 [ 8 10]]


In [50]:
a1 = np.array([[1,4], [1,3]])
print(a1)
a1.sum(axis=0) # sum of each column

[[1 4]
 [1 3]]


array([2, 7])

In [59]:
a1 = np.array([[1,4], [1,3]])
print(a1)
print('sum of each row:',a1.sum(axis=1)) 
print('min of each row:', a1.min(axis=1)) 
print('cumulative sum along each row:\n',a1.cumsum(axis=1))
#change axis to 0 for columns

[[1 4]
 [1 3]]
sum of each row: [5 4]
min of each row: [1 1]
cumulative sum along each row:
 [[1 5]
 [1 4]]


In [79]:
# universal functions
# element-wise also
# math funcs such as sin, cos, exp, sqrt, etc.
a1 = np.array([[1,4], [1,3]])
a2 = np.array([[2,0], [3,5]])
print('a1\n', a1)
print('a2\n', a2)
print(np.exp(a1)) 
print(np.sqrt(a1)) 
print(np.add(a1,a2))

a1
 [[1 4]
 [1 3]]
a2
 [[2 0]
 [3 5]]
[[ 2.71828183 54.59815003]
 [ 2.71828183 20.08553692]]
[[1.         2.        ]
 [1.         1.73205081]]
[[3 4]
 [4 8]]


### Indexing, Slicing, Iterating

In [81]:
# 1d array
a = np.arange(0,100, 5)
print(a)
print(a[2])
print(a[2:5])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
10
[10 15 20]


In [119]:
b = np.arange(0,20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [95]:
b[2,3]

11

In [96]:
b[2,3] = 12
b

In [98]:
b[0:5, 1] # value in each row in second column

array([ 1,  5,  9, 13, 17])

In [101]:
b[1:4,:] # all columns' values
#in second, third, and fourth row of b

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 12],
       [12, 13, 14, 15]])

In [102]:
# iterating:
for row in b:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 12]
[12 13 14 15]
[16 17 18 19]


In [103]:
for elem in b.flat:
    print(elem)

0
1
2
3
4
5
6
7
8
9
10
12
12
13
14
15
16
17
18
19


### Reshaping, Transposing

In [118]:
c = b.reshape(2,10)

In [121]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [120]:
b.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [123]:
b.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

#### More Computations
`array 1 + array2
array1 * array2
np.dot(array1, array2)
np.mean
np.max(array, axis = None) # or '0' for column-wise, or '1' for row-wise
np.maximum(array1, array2)
np.min(array, axis = None) # or '0' for column-wise, or '1' for row-wise
np.minimum(array1, array2)
np.median
np.cumsum
np.sqrt
np.exp
np.add
np.subtract
`

