# pandas - DataFrames



- useful data structure in pandas
- similar to spreadsheet 
- rows, columns
- first row: column headings
- pandas can internally index each row starting from 0.
- we can explicitly specify an index for each row <example below>

In [7]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [8]:
tim_gr=[65,80,80]
nanda_gr=[80,80,90]
juan_gr=[90,95,95]

In [9]:
df=DataFrame([tim_gr, nanda_gr, juan_gr], index=['Tim','Nanda','Juan'], columns=['CIS','ACC','MKT'])
print(df)

       CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90
Juan    90   95   95


In [22]:
gr_book=np.array([tim_gr, nanda_gr, juan_gr])
print(gr_book)

[[65 80 80]
 [80 80 90]
 [90 95 95]]


In [23]:
df1=DataFrame(gr_book, index=['Tim','Nanda','Juan'],columns=['CIS','ACC','MKT'])
print(df1)

       CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90
Juan    90   95   95


In [10]:
# Examining column names

df.columns

Index(['CIS', 'ACC', 'MKT'], dtype='object')

In [12]:
# accessing values in  certain columns

df['CIS']

Tim      65
Nanda    80
Juan     90
Name: CIS, dtype: int64

In [10]:
# accessing rows
#df.head()
#df.tail()
df.head() 

CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90
Juan    90   95   95

In [16]:
# accessing rows by index labels
df.loc[['Tim','Juan']]

CIS  ACC  MKT
Tim    65   80   80
Juan   90   95   95

In [13]:
# accessing rows by index numbers
df.iloc[:2]

CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90

In [17]:
## accessing certain rows & certain columns
df[['CIS','MKT']].loc[['Tim','Juan']]

CIS  MKT
Tim    65   80
Juan   90   95

In [15]:
# number of rows and columns
print(len(df))
print(len(df.columns))

3
3


In [17]:
# counts for each value in column CIS
type_count = df['CIS'].value_counts()
type_count

90    1
65    1
80    1
Name: CIS, dtype: int64

In [20]:
# same as cell above, using groupby func
x=df.groupby('CIS').size()
x

CIS
65    1
80    1
90    1
dtype: int64

``
dataframe['col_name'].describe()
dataframe['col_name'].mean()
dataframe['col_name'].min()
dataframe['col_name'].max()
dataframe.T``



## Pandas Basic Uses
## Example: Hospital Data

In [29]:
df = pd.read_csv('Hospital_Data.csv')

Source: https://www.medicare.gov/hospitalcompare/about/hospital-overall-ratings.html

- The data contains information about hospitals across the U.S, including Provider ID, Hospital Name, Address, City/State, Hospital Type, Hospital ownership, Emergency services, Overall Rating (1-5 scale) etc.

- The Hospital Overall Rating score is computed from up to 57 quality measures across 7 areas of quality (some hospitals have less measures, as few as 9, some have more, as many as 57, the average is about 39 measures). 

- The 7 areas of quality are: Mortality, Safety of Care, Readmission, Patient Experience, Effectiveness of Care, Timeliness of Care, Efficient Use of Medical Imaging.

### In this example, we want to compare the # of hospitals and the mean overall ratings across the US,  hospital types, hospital ownerships, etc.

In [116]:
df.head() # first few rows

ProviderID                        HospitalName                     Address  \
0       10005       MARSHALL MEDICAL CENTER SOUTH  2505 U S HIGHWAY 431 NORTH   
1       10012      DEKALB REGIONAL MEDICAL CENTER        200 MED CENTER DRIVE   
2       10095                HALE COUNTY HOSPITAL            508 GREEN STREET   
3       10131            CRESTWOOD MEDICAL CENTER          ONE HOSPITAL DR SE   
4       20018  YUKON KUSKOKWIM DELTA REG HOSPITAL                  PO BOX 287   

         City State  ZIPCode CountyName  PhoneNumber          HospitalType  \
0        BOAZ    AL    35957   MARSHALL   2565938310  Acute Care Hospitals   
1  FORT PAYNE    AL    35968    DE KALB   2568453150  Acute Care Hospitals   
2  GREENSBORO    AL    36744       HALE   3346243024  Acute Care Hospitals   
3  HUNTSVILLE    AL    35801    MADISON   2568823100  Acute Care Hospitals   
4      BETHEL    AK    99559     BETHEL   9075436300  Acute Care Hospitals   

                             HospitalOwnership   ...     \
0  Government - Hospital District or Authority   ...      
1                                  Proprietary   ...      
2  Government - Hospital District or Authority   ...      
3                                  Proprietary   ...      
4                                       Tribal   ...      

   Patientexperiencenationalcomparison  \
0         Same as the national average   
1           Below the national average   
2                        Not Available   
3           Below the national average   
4           Below the national average   

         Patientexperiencenationalcomparisonfootnote  \
0                                                NaN   
1                                                NaN   
2  There are too few measures or measure groups r...   
3                                                NaN   
4                                                NaN   

   Effectivenessofcarenationalcomparison  \
0           Same as the national average   
1           Same as the national average   
2           Same as the national average   
3           Same as the national average   
4           Same as the national average   

  Effectivenessofcarenationalcomparisonfootnote  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   

  Timelinessofcarenationalcomparison  \
0         Above the national average   
1         Above the national average   
2       Same as the national average   
3         Below the national average   
4                      Not Available   

          Timelinessofcarenationalcomparisonfootnote  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4  Results are not available for this reporting p...   

  Efficientuseofmedicalimagingnationalcomparison  \
0                     Below the national average   
1                   Same as the national average   
2                                  Not Available   
3                   Same as the national average   
4                                  Not Available   

  Efficientuseofmedicalimagingnationalcomparisonfootnote  \
0                                                NaN       
1                                                NaN       
2  Results are not available for this reporting p...       
3                                                NaN       
4  There are too few measures or measure groups r...       

                              Location filter_$  
0  2505 U S HIGHWAY 431 NORTH BOAZ, AL        1  
1  200 MED CENTER DRIVE FORT PAYNE, AL        1  
2      508 GREEN STREET GREENSBORO, AL        1  
3    ONE HOSPITAL DR SE HUNTSVILLE, AL        1  
4                PO BOX 287 

In [ ]:
df.tail() # last few rows 

In [30]:
df.columns # list names of columns

Index(['ProviderID', 'HospitalName', 'Address', 'City', 'State', 'ZIPCode',
       'CountyName', 'PhoneNumber', 'HospitalType', 'HospitalOwnership',
       'EmergencyServices', 'MeetscriteriaformeaningfuluseofEHRs',
       'Hospitaloverallrating', 'Hospitaloverallratingfootnote',
       'Mortalitynationalcomparison', 'Mortalitynationalcomparisonfootnote',
       'Safetyofcarenationalcomparison',
       'Safetyofcarenationalcomparisonfootnote',
       'Readmissionnationalcomparison',
       'Readmissionnationalcomparisonfootnote',
       'Patientexperiencenationalcomparison',
       'Patientexperiencenationalcomparisonfootnote',
       'Effectivenessofcarenationalcomparison',
       'Effectivenessofcarenationalcomparisonfootnote',
       'Timelinessofcarenationalcomparison',
       'Timelinessofcarenationalcomparisonfootnote',
       'Efficientuseofmedicalimagingnationalcomparison',
       'Efficientuseofmedicalimagingnationalcomparisonfootnote', 'Location',
       'filter_$'],
      dt

In [28]:
# descriptive statistics for Hospital Overall Ratings
df['Hospitaloverallrating'].describe()

count    3675.000000
mean        3.151020
std         1.068577
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Hospitaloverallrating, dtype: float64

In [66]:
# number of hospitals in each rating score, automatically sorted 
rating_count = df['Hospitaloverallrating'].value_counts()
print(rating_count)

3    1178
4    1153
2     750
5     335
1     259
Name: Hospitaloverallrating, dtype: int64


In [69]:
# AVG HOSPITAL OVERAL RATINGS FOR EACH HOSPITAL TYPE
avg_rating_hosptype = df.groupby('HospitalType')['Hospitaloverallrating'].mean()
print(type(avg_rating_hosptype)) #avg_rating_hosptype is of pandas series type, values in HospitalType columns are used as indices
avg_rating_hosptype

<class 'pandas.core.series.Series'>


HospitalType
Acute Care Hospitals         3.075372
Critical Access Hospitals    3.503077
Name: Hospitaloverallrating, dtype: float64

In [70]:
# same results as above, nicer output (HospitalType values are not treated as indices, avg_rating_hosptype2 is of pandas dataframe type)
avg_rating_hosptype2 = df.groupby('HospitalType', as_index=False)['Hospitaloverallrating'].mean()
print(type(avg_rating_hosptype2))
avg_rating_hosptype2

<class 'pandas.core.frame.DataFrame'>


HospitalType  Hospitaloverallrating
0       Acute Care Hospitals               3.075372
1  Critical Access Hospitals               3.503077

In [91]:
# NUMBER OF HOSPITALS W/ & W/O EMERGENCY SERVICES (1 means with, 0 means without)
emergency_count = df['EmergencyServices'].value_counts()
print(type(emergency_count)) # pandas series type
emergency_count

<class 'pandas.core.series.Series'>


1    3500
0     175
Name: EmergencyServices, dtype: int64

In [108]:
# nicer output
emergency_count2 = df['EmergencyServices'].value_counts()
emergency_count2 = pd.DataFrame([emergency_count])  # convert series to dataframe
emergency_count2 = emergency_count2.T # transpose dataframe 
emergency_count2.reset_index(level=0, inplace=True) 
emergency_count2.columns = ['EmergencyServices','NumberofHospitals'] # rename columns
emergency_count2

EmergencyServices  NumberofHospitals
0                  1               3500
1                  0                175

In [113]:
# Mean ratings for each hospital ownership type
mean_ratings_ownership = df.groupby('HospitalOwnership', as_index=False)['Hospitaloverallrating'].mean()
mean_ratings_ownership

HospitalOwnership  Hospitaloverallrating
0                         Government - Federal               2.500000
1  Government - Hospital District or Authority               3.060241
2                           Government - Local               3.092664
3                           Government - State               2.744186
4                                    Physician               4.000000
5                                  Proprietary               2.821767
6                                       Tribal               3.250000
7                Voluntary non-profit - Church               3.284281
8                 Voluntary non-profit - Other               3.341667
9               Voluntary non-profit - Private               3.238376

In [115]:
# Which hospital ownership type has highest mean ratings?

# select the row from mean_ratings_ownership dataframe with the highest value in the Hospitaloverallrating column
mean_ratings_ownership[mean_ratings_ownership['Hospitaloverallrating'] == mean_ratings_ownership['Hospitaloverallrating'].max()]

HospitalOwnership  Hospitaloverallrating
4         Physician                    4.0